### ISSUE TITLE
Hyperdrive Replication Issues

### ISSUE THREAD

**Issue by joehand** [mafintosh/hypercore-archiver#1]
This is a few issues, but may be related:
### Discovery Key Issues

I had an issue adding the hyperdrive archive key as a string to the database. The discovery key ended up different if I used a string vs buffer.

``` js
var coreArchive = require('hypercore-archive')('/dir')

var archive = drive.createArchive()
var archiveKey = archive.key

coreArchive.add(archiveKey) // okay
coreArchive.add(archiveKey.toString('hex')) // not okay
```

If `add` should accept strings then we just need to fix that. Or make sure its documented that only buffers are accepted.
### Metadata + Content

**(EDIT: this worked nevermind!)**

EDIT Also: But they ended up in two different directories. Is that how it is supposed to work?

**Comment by mafintosh** [comment]
## Metadata + Content

Yes thats exactly how its supposed to work :)

**Comment by mafintosh** [comment]
strings are also accepted now
