### ISSUE TITLE
In non-passive replication, listen for added archives and request them

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hypercore-archiver#12]
My beaker-debugging adventures have led to me discover that, if an existing connection is established between Beaker and Hypercloud when I add a new dat, then replication won't occur. Both B and HC are joining the swarm, and ignoring the already-established connection.

That can be fixed in non-passive replication by listening for the 'add' event and adding the request then. https://github.com/mafintosh/hypercore-archiver/blob/master/index.js#L98

**Comment by mafintosh** [comment]
should be fixed

**Comment by pfrazee** [comment]
What did you do to fix this?

**Comment by mafintosh** [comment]
One side is always the initiator. If we are initiating, join first. The other side will follow
