### ISSUE TITLE
sparse mode

### ISSUE THREAD

**Issue by okdistribute** [mafintosh/hypercore-archiver#16]
like `content: false` mode, except `sparse: true` would still replicate content, just only the content that is being asked for! :)

**Comment by joehand** [comment]
Right now raf stores all the data for a feed in a single file. If the feed has `sparse: true` a file is created for the size of the content, even though a lot of the file is empty.

* Is there a way we can use a single file storage but not have the file be created with empty bytes?
* OR Should we use some other storage for sparse content feeds?

**Comment by mafintosh** [comment]
@joehand https://github.com/mafintosh/random-access-page-files

**Comment by mafintosh** [comment]
@joehand yea there is a way to keep it as a single file as well using the same technique. if you need that let me know and i'll write a module for it
