### ISSUE TITLE
archive.on('archived') should fire when both feeds are done for archives

### ISSUE THREAD

**Issue by joehand** [mafintosh/hypercore-archiver#4]
Currently `archive.on('archived')` fires for each individual feed that finishes. 

If the feed is a metadata archive, it should not fire until the content feed is also done. Then it should fire with:

```js
archive.on('archived', function (key, metadataFeed, contentFeed) {

})
```

**Comment by mafintosh** [comment]
👍

**Comment by mafintosh** [comment]
does now in latest (event is called sync for consistency)
